# Generated by Django 2.2 on 2020-06-04 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('picture', models.FileField(null=True, upload_to='')),
                ('genre', models.CharField(max_length=150, null=True)),
                ('album_added', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='albumCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=150, null=True)),
                ('song_file', models.FileField(null=True, upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('song_album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='song_album', to='music_app.album')),
            ],
        ),
        migrations.CreateModel(
            name='favoriteSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite', to=settings.AUTH_USER_MODEL)),
                ('songs_list', models.ManyToManyField(related_name='fav_song', to='music_app.song')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_album', to='music_app.albumCategory'),
        ),
    ]
