# Generated by Django 2.2 on 2020-06-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
