# Generated by Django 2.2 on 2020-06-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_song_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestedSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_requested_songs', models.ManyToManyField(related_name='all_requested_songs', to='music_app.song')),
            ],
        ),
    ]
