# Generated by Django 2.2 on 2020-06-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0003_requestedsong'),
    ]

    operations = [
        migrations.DeleteModel(
            name='requestedSong',
        ),
    ]
