# Generated by Django 2.2 on 2020-06-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_delete_requestedsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumcategory',
            name='category_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
