# Generated by Django 2.2 on 2020-06-05 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_albumcategory_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritesong',
            name='belongs_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
