# Generated by Django 2.2 on 2020-06-05 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_app', '0006_auto_20200605_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='extendedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000, null=True)),
                ('age', models.IntegerField(null=True)),
                ('belongs_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_reverse', to=settings.AUTH_USER_MODEL)),
                ('songs_list', models.ManyToManyField(related_name='fav_song', to='music_app.song')),
            ],
        ),
        migrations.DeleteModel(
            name='favoriteSong',
        ),
    ]
