# Generated by Django 2.2 on 2020-06-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0007_auto_20200605_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='description',
        ),
    ]
