# Generated by Django 2.2 on 2020-06-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0009_song_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_favourite',
        ),
        migrations.AlterField(
            model_name='song',
            name='song_album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='album_song', to='music_app.album'),
        ),
    ]
